spring.application.name=auth-sys

spring.datasource.url=jdbc:mysql://localhost:3306/auth_sys
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
